# Generated by Django 4.2.7 on 2023-11-16 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theportfolio', '0002_rename_body_post_content_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
