# Generated by Django 4.2.7 on 2023-11-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theportfolio', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='post',
        ),
    ]
