# Generated by Django 4.2.7 on 2023-11-19 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theportfolio', '0005_rename_author_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
