# Generated by Django 4.2.7 on 2023-11-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theportfolio', '0013_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
