# Generated by Django 3.2.18 on 2023-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Estudande', 'Sou um Estudante'), ('Professor', 'Sou um Professor')], default='Estudande', max_length=10),
        ),
    ]
