# Generated by Django 3.2.18 on 2023-11-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Estudante', 'Sou um Estudante'), ('Professor', 'Sou um Professor')], default='Estudante', max_length=10),
        ),
    ]
