# Generated by Django 4.2.7 on 2023-11-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poliplanner', '0011_category_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
