# Generated by Django 4.2.7 on 2023-11-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poliplanner', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
