# Generated by Django 4.2.7 on 2023-11-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poliplanner', '0021_rename_post_tarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='tarefa_single', to='poliplanner.subject'),
        ),
    ]
